import Head from "next/head";

import Coins from "../components/Coins";

export default function Home({ coins }) {
  // console.log(coins);
  const coinsData = coins.data;
  // console.log(coinsData);

  return (
    <div className="bg-gray-100">
      <Head>
        <title>Crypto Data Collection</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="py-10 ">
        {/* Front Header Section */}
        <div className=" flex flex-col items-center py-40">
          <h2 className="text-5xl font-bold py-2 ">
            Hello Developers... 🔥🔥🔥 <sup>🚀</sup>{" "}
          </h2>
          <p className="text-xl font-medium">
            Basic CryptoCurrency Price Taker Application...{" "}
          </p>
        </div>
        <div className="my-20">
          <Coins coinsData={coinsData} />
        </div>
      </main>
    </div>
  );
}

export async function getServerSideProps(context) {
  const coins = await fetch(
    "https://pro-api.coinmarketcap.com/v1/cryptocurrency/listings/latest",
    {
      method: "GET",
      headers: { "X-CMC_PRO_API_KEY": "195e47ad-c0e2-4a1e-b52f-4cf14b52f85a" },
    }
  ).then((res) => res.json());

  return {
    props: { coins },
  };
}
